### ISSUE TITLE
How to export

### ISSUE THREAD

**Issue by luca-panjer** [Syrious/Processing-Starter-For-External-IDE#1]
Hi,

In the processing IDE there is an option for exporting a application to a specific platform.
How would you about doing that here?

I tried building a jarfile as a intellij module and this works, mostly, except some weird quirks sometimes like PGraphics not rendering.
I think this is because the native linux binaries arent included when building it like this. They are included when I export it to linux from the IDE. Also, the embedded java option is really really useful.

Thanks for this project, it's really helpful!

**Comment by Syrious** [comment]
Hey,

I just added a short [wiki ](https://github.com/Syrious/Processing-Starter-For-External-IDE/wiki/Building-a-jar-file-with-Intellij-IDEA) on how to build a jar file in IntelliJ. 

If it helps, give me a short notice :)

**Comment by luca-panjer** [comment]
Thank you, but that is how far I've gotten myself already :)

What I'm looking for is how to make a platform specific build with the platform specific processing libraries compiled with it.

**Comment by Syrious** [comment]
Actually, all Java builds should be platform independent. That's the selling point of Java.  

I just built the example on Windows, copied the .jar-file over to Ubuntu and ran it. It worked without a problem.

Do you have different Java versions on Windows and Linux?

**Comment by luca-panjer** [comment]
Java might be the same, but I think there are platform specifics.

If you examine a windows export:
![image](https://user-images.githubusercontent.com/10108352/170991277-17ce3488-eb03-4e94-8d90-1c6571c248f3.png)
You find DLL files

If you examine a linux export:
![image](https://user-images.githubusercontent.com/10108352/170991328-a22ac18d-e406-455c-b7d5-73665487cb3e.png)

You find SO files

**Comment by luca-panjer** [comment]
This is the main issue I am having:

My UI looks like this in windows:
![image](https://user-images.githubusercontent.com/10108352/171005046-48733690-3132-4901-8510-368184addbf9.png)

And like this on raspbian:
![image](https://user-images.githubusercontent.com/10108352/171005192-235eb9af-1de2-40fe-9f2f-4350e40ed398.png)

I think this is due to the fact that this circle is drawn as a pgraphics object. It get's drawn into a PGraphics buffer at startup and then that buffer gets drawn every frame. This has quite a significant performance boost for us.

**Comment by Syrious** [comment]
Ah I see. To be honest I never used Processing IDE myself and actually I am not really doing anything with the Processing Framework. Hence I never used the export functionality. 

By the look of the [Processing Github repo](https://github.com/processing/processing/tree/master/app/lib), they seem to use [JNA](https://github.com/java-native-access/jna) for accessing platform native libraries and  ANT for their build process. Probably there might be a way of doing the same outside the Processing IDE but I don't even know why they need to wrap java-code like that. 
I try to find something on how to setup a ant build.

Edit: Just saw your screenshots. Is it a requirement to use Processing? I think you could easily achieve a GUI with AWT, Swing or JavaFX

**Comment by luca-panjer** [comment]
No, it's not a requirement. But we have all our code in Processing atm.

Is AWT, Spring or JavaFX similar to processing so it would be easy to port?

**Comment by Syrious** [comment]
Well, AWT, Swing and JavaFX are Toolkits integrated in the JDK for building GUIs, where AWT is the oldest and JavaFX the newest.
I found that JavaFX was quite easy to learn but could also be a bit overkill. I'd suggest you  check all of them out.

But for now, as a workaround you could of course rename all your .java-files to .pde. Then open the Main.pde in Processing IDE and try to fix the import errors (since Processing doesn't need itself as external library) and export it to the platform you want. 

Probably this could also be automated via scripts, but would be a bit hacky I guess

**Comment by luca-panjer** [comment]
Would this work with folders etc. as well?

Also my project references another idea project, just toss toss all the files in together and rename to pde?

**Comment by Syrious** [comment]
I haven't tried it with a folder structure. There is a high chance Processing don't understand folder/package structures.


> Also my project references another idea project, just toss toss all the files in together and rename to pde?

Yeah, pretty much. But try it first on a small project. I'm not sure how easy it is to clean code up so that Processing IDE won't complain.
